apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency-converter-api
  labels:
    app: currency-converter-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: currency-converter-api
  template:
    metadata:
      labels:
        app: currency-converter-api
    spec:
      containers:
        - name: currency-converter
          image: <docker-username>/currency-converter-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production