apiVersion: v1
kind: Service
metadata:
  name: currency-converter-service
spec:
  selector:
    app: currency-converter
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP